name: 'Patch properties of YAML content inside YAML files'
description: 'This github action can patch properties of stringified YAML content inside YAML files'
author: 'René Kretzschmar'
inputs:
  documentFile:
    required: true
    description: 'The path to the YAML document file to be patched'
  yamlPath:
    required: true
    description: 'The YAML path of the property to be patched'
  yamlInsideYamlPath:
    required: false
    description: 'The optional YAML path of the property to be patched inside the stringified YAML at `yamlPath`'
  newValue:
    required: true
    description: 'The new value'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: align-justify
  color: green
