name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp ./__tests__/fixtures/test.yaml ./test_.yaml
      - uses: ./
        with:
          documentFile: ./test_.yaml
          yamlPath: level1.level2.yamlInsideYaml
          yamlInsideYamlPath: backend.image.tag
          newValue: 1.1.0
      - run: cat ./test_.yaml
      - run: cp ./__tests__/fixtures/test.yaml ./test_.yaml
      - uses: ./
        with:
          documentFile: ./test_.yaml
          yamlPath: level1.primitive
          newValue: patched value
      - run: cat ./test_.yaml
